#! /bin/sh

# Run the tests with FPC
rm -fr fpc-build
mkdir fpc-build
cd fpc-build

if test -z "$FPC";
then
    FPC="/usr/lib/fpc/*/ppc*"
fi

for f in ../*.pas;
do
    # Try with different versions and modes until something works
    # *nix only at the moment
    for fpc in $FPC;
    do
        # Try to do most things in default mode
        # Go for EP next, for things not implemented in default mode
        # ISO should be last (and only for versions without an EP mode)
        # Primarily to see the lowest version that can handle these things, and in which mode
        for mode in fpc extendedpascal iso;
        do
            $fpc -FE. -FU. -M$mode $f
            err=$?
            if test "$err" = "0";
            then
                version=`echo $fpc | grep -Po '\d+\.\d+\.\d+'`
                if test -z "$version";
                then
                    version=$($fpc -iV)
                fi
                echo "$f ($version, $mode)" >> success
                break 2;
            fi
        done
    done

    if test "$err" != "0";
    then
        echo "$f" >> failure
    fi
done
