#! /bin/sh
# vi: et:sts=4:sw=4:ts=4

# Run the tests with GPC
rm -fr gpc-build
mkdir gpc-build
cd gpc-build

# mods.int.pas has to be compiled before mods.imp.pas for mods.imp.pas to successfully compile
for f in ../mods.int.pas `find .. -name '*.pas' -a ! -path '../mods.int.pas'`;
do
    out=`echo $f|sed -e 's/^\.\.\/\(.\+\)\.pas$/\1/g'`
    # Try to compile
    gpc -o $out $f --automake --unit-path=..

    if test "$?" == "0";
    then
        echo "$f" >> success
    else
        # If it was a module or unit, linking will have failed
        # Let's try again without linking
        gpc -c $f
        if test "$?" == "0";
        then
            echo "$f" >> success
        else
            echo "$f" >> failure
        fi
    fi
done
